# Generated by Django 4.1.1 on 2022-09-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_negocio', models.IntegerField(choices=[(1, 'restaurante'), (2, 'drogueria')], default=1, null=True, verbose_name='Tipo de Negocio')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción del requerimiento')),
            ],
        ),
    ]
