# Generated by Django 3.2.8 on 2022-10-02 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_negocio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_negocio', models.IntegerField(blank=True, null=True, verbose_name='Tipo de Negocio')),
                ('nombre_tipo_negocio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del nuevo tipo de negocio')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='id_tipo_negocio',
        ),
        migrations.AddField(
            model_name='item',
            name='tipo_negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tipo_negocio'),
        ),
    ]
