# Generated by Django 3.2.8 on 2022-10-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo_negocio',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tipo_negocio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='negocio',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tipo_negocio'),
        ),
    ]
