# Generated by Django 3.2.8 on 2022-10-04 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_auto_20221003_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado_cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checked', models.BooleanField(default=False, null=True)),
                ('requerimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.item')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario')),
            ],
        ),
    ]
