# Generated by Django 3.2.8 on 2022-10-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_resultado_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado_cliente',
            name='requerimiento',
        ),
        migrations.AddField(
            model_name='resultado_cliente',
            name='requerimiento',
            field=models.ManyToManyField(blank=True, null=True, to='aplicacion.Item'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='negocio',
        ),
        migrations.AddField(
            model_name='usuario',
            name='negocio',
            field=models.ManyToManyField(blank=True, default=1, null=True, to='aplicacion.Tipo_negocio'),
        ),
    ]
