# Generated by Django 3.2.8 on 2022-10-05 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_auto_20221004_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='negocio',
        ),
        migrations.AddField(
            model_name='usuario',
            name='negocio',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tipo_negocio'),
        ),
    ]
