# Generated by Django 3.2.8 on 2022-10-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_auto_20221004_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado_cliente',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='checked'),
        ),
    ]
